version: '3.1'
services:
  database:
    image: mariadb
    restart: always
    env_file:
      - .env

  server:
    build: server
    image: zakrywilson/dvd_library_service
    ports:
      - "8080:8080"
    env_file:
      - .env
    links:
      - database
