version: '2.0'

services:
  database:
    image: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      backend:
        aliases:
          - database
          - mariadb
  server:
    build: server
    image: zakrywilson/movie_library_service
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - service
    links:
      - database

networks:
  backend:

